name = "thorrim-bot"
main = "src/worker.ts"
compatibility_date = "2025-12-15"

[vars]
DISCORD_PUBLIC_KEY = "YOUR_APP_PUBLIC_KEY"
DISCORD_APPLICATION_ID = "YOUR_APP_ID"
DISCORD_BOT_TOKEN = "YOUR_BOT_TOKEN"
